using UnityEngine;

//The purpose of this script is to practice making collectible lore items that will be hidden in the game. 
public class AppleSause : MonoBehaviour
{
	public string collectable = "Collectable Get";
	public float collected =1f;

	public void Collectables(float value)
	{
		collectable = collectable;
	}
}

// Use this for initialization
	//public void OnEnable()
	
	//	Debug.Log("You're right, I'm fine");
		
		//Hidden Game Story:
		//This mourning I got a email from my scripting class. I assume it was my teacher who sent it out. It was an invitation to download an app to learn code better. so I downloaded it. I practiced and found that it was helping. In the past few days I have been so miserable that when i was on this app I was suddenly addicted to doing my homework. And it didn't really count but it made me feel better so what does it matter if I get a grade for it or not.
		//Today wasn't so bad at all. I'm still pretty stuffed up with mucus but my rabbit MacBeth hopped on my lap 3 times today and I discovered that he loves chips and salsa, Alot! Perhaps i'll take things at my own pace. I confronted my manager today in person and was even able to file some orders for my family from the goods that I had been selling this week. I feel like an over aged girl scout but at least I feel better. I get to go to school tomorrow!
	

	//public void OnDisable()
	
		//Debug.Log("I've Had a horrible day");
		//if (OnDisable(Destroy(obj: );
		
		
		// Hidden game story;
        //For the past week I was training for a job where I thought I'd be customer service rep over the phone for a product of a company but it turned out that I was going to be a sales rep. "private contractor" aka Door salesmen for cutco. At first I was pumped but then I started to feel uneasy about the way I was getting paid and how I was making sales. I did the job I was asked to do and made some sales but it took me longer then an hour and I was starting to feel like the $17 an hour I was promised was a half truth because in reality I'd only be paid per demo. Which, like I said before took me longer than an hour to do. I was also required to sell to my friends and family before anything else and I could only work further based off of the refferals I was given by my family to "practice demo" with. I was starting to feel like a horrible person and started to fear that my friends and family were only selling to me because they felt bad about my situation. Anyway I've decided to confront my manager over the phone and she seemed genuinly sorry about the mis-communication on how we operate. I'm still unsure. So tomorrow I'll go in and confront her face to face. I'll be prepaired to leave all my stuff at the office incase I have to quit then and there. I would much rather tell my dad that I didn't feel confidednt enough in the company and so he won't receive the genuinly good product he ordered rather then to find out I was being used to emotionally "scientifically' manipulate my family into buying a product for a company that refuses to set up an online shop at least.
        //Fasforward to today I've officially been selling for two days out of mandatory no pay three day training and I have sevier alargies from travaling around and using up my gas, still haven't been paid. I cancel all my appointments for today because I can bairly breath. My mom has consistantly forgotten to get my medicin from the walgreens all week so today she comes in my room and tells me that I need to go get my meds today and tells me to get hers as well. Fine no big deal. I'm struggling to drive cause my eyes are burning from my alergies and all I can think about is how if I had not come to my senses at the last stop light I could have pottentialy murdered somestranger myself and my little brothers who are in the back seat at the time. Luckly I succeed at fighting against my sleep deprived mind. The man at the walgreens was very nice and didn't pester me about my state of appearence or joke around. Which was very appreciated. Anyway I drive home and I decide to call my mom to ask if she'll let me use her card to get a frazle she says yes. I proceed to go wash the stupid frazel refill cup we got early this summer. I get to the gastation that i always go to because it's the closest and thats where I go to get the frazels. Anyway I get to the desk and the cashier dosen't even let me get close to the counter before she tells me I can't refill that cup. the cup that I got there alittle more then 2 mounths ago. the cup that gueranteed that if I baught it I could have unlimited refills for only a $1 for as long as I had the cup. I said The sup says I can by refills in my tired I really don't care about anything at all voice. She gets offended. We have never done that here and our frazel machine hasn't worked for 2 years. I'm here thinking I litterally don't care about this and also no you have had those machines I baught this here and I've lived here and come to this gastation for over 2 years. Anyway long story short I sit there and listen tiredly for her to either tell me to dump it out or scan the bar code on the side of the cup that says refill. I wait and I wait still keeping my distance from the counter until her manager comes in and just inputs the price into the cash regester. I was pretty surprised that the manager also insisted that the machenes hadsn't been running for years because I thought I had a good relationship with the manager but guess not. She acted as if she had never seen me and I suppose it didn't help that to her I probobly looked like a drug addict she could get away with mistreating and pretending like I'm the crazy person
        //who baught a unlimited cup from a different gastation a few years back and some how had delusions that I came in on a regular basis and got refills but whatever. I left without saying much I didn't feel in the mood to defend myself.
        //Anyway I missed school in order to get a job at a place that tells alot of half truths, fell behind on homework, I feel pretty under valused as a human and my mom is being a hypocrit. I admit I was pretty boiled when I went to change my laundry to find that they had been washed with my 6 yearold brothers poopy underware. But having my mom come in and comand me to change my attatude while she proceeds to shove my clothes back into the washer, fill up the soap thing and restart my clothes slaming the door and then preceeding to ask me if there'll be anything else I need while walking away into her room just to storm back out of her room clearly mad that I put my brothers clean clothes on her bed to ask me if there will be anything else since I thought it was so Ok to put my brothers freshly dried clothes on her bed while I was changing the laundry. I didn't want to start a fight and it helped that I was already pretty numb from existing in the moment I just said no and went upstairs to wash my face. As I went Upsatirs she commanded me again to change my attitude as she agrely went back to her room. then While I was washing my face with hot water she went past the door into my room unpluged my phone and put hers on my charger came back to the bathroom door told me her phone is charging and that she'd get it when she was done smoking. I got done washing my face having not said a word since I was downstairs and went to my room. Here I am type still having not spoken.
        //I've been thinking to myself this whole time. Reveiwing the past week, going even further into the past. I relized that I would be just as misserable now as if I was homeless and nobody was here. I relised that if I disappeared my mom might spend 3 days and no longer looking for me. She would call the cops sure. she would track my phone, contact my other family members and any friends she knew. She'd go to the exstent that would make it understandable for people to veiw her as greiving. but when I tell her I'm upset she tells me that i should do something about that. I should change my attitude. when She walks into my room and sees me on my computer it doesn't matter what I'm doing she often cals it crap, a waste of time , or lazyness. I want to animate and make video games and all she see's is me being lazy, me throwing a tantrum, I'm not unlucky I just cause bad things that I can't controll to happen to me. I don't have a hard time remebering names and numbers I just don't care. I don't know what it's like to love someone because I've never had sex. I love my mom, but I guess that doesn't count despite how cruel and unsympathetic she is sometimes. I feel like I have always been there for her. It's just only convinient for her if I'm protecting her no questions asked.
        //I wouldn't be surprised that if I disappeared the first thing she'd do is get rid of my rabbit, start selling my things or give them away"out of the kindness of her heart" or because "it's what I would have wanted" As soon as Im inconvinient as soon as I'm not interesting enough for the narrative I'm the problem that's easy to excuse away. She's human, but it seems noone else is allowed to be.
        //I just want to finish college and move. She's hasn't helped me with any of that. Just talk. The reason I've been able to go to college is because I work hard to get good grades. I used all that was left over from my grant last year to pay for the rent my mom is supposed to be paying. I did that 3 times ruffly $4,000 of my student aid went to rent because my mom fails to not spend her mony on nights out with clients and friends. She fails not to drive drunk, she fails to not buy ciggerets, she fails to pay for her little kids schooling, fails to be attracted to men who are'n crazy and just want to fuck. She fails on every level to act like an adult mom who has a responsibility to her family and self. I'm so tired of her problems being my problems just because I came out of the wrong god damn pussy!
	